sbatch cc_2_models_noeff_high_egp_som10.sh
sbatch cc_2_models_noeff_high_egp_som25.sh
# sbatch cc_2_models_noeff_high_egp_som25_sam02.sh
# sbatch cc_2_models_noeff_high_egp_som25_sam005.sh
sbatch cc_2_models_noeff_high_egp_som25_unequal.sh
sbatch cc_2_models_noeff_high_egp_som50.sh
sbatch cc_2_models_noeff_high_match.sh
# sbatch cc_2_models_noeff_high_match_sam02.sh
# sbatch cc_2_models_noeff_high_match_sam005.sh

sbatch cc_2_models_noeff_low_egp_som10.sh
sbatch cc_2_models_noeff_low_egp_som25.sh
# sbatch cc_2_models_noeff_low_egp_som25_sam02.sh
# sbatch cc_2_models_noeff_low_egp_som25_sam005.sh
sbatch cc_2_models_noeff_low_egp_som25_unequal.sh
sbatch cc_2_models_noeff_low_egp_som50.sh
sbatch cc_2_models_noeff_low_match.sh

sbatch cc_2_models_noeff_tweedie_high_egp_som10.sh
sbatch cc_2_models_noeff_tweedie_high_egp_som25.sh
# sbatch cc_2_models_noeff_tweedie_high_egp_som25_sam02.sh
# sbatch cc_2_models_noeff_tweedie_high_egp_som25_sam005.sh
sbatch cc_2_models_noeff_tweedie_high_egp_som25_unequal.sh
sbatch cc_2_models_noeff_tweedie_high_egp_som50.sh
sbatch cc_2_models_noeff_tweedie_high_match.sh

sbatch cc_2_models_noeff_tweedie_low_egp_som10.sh
sbatch cc_2_models_noeff_tweedie_low_egp_som25.sh
# sbatch cc_2_models_noeff_tweedie_low_egp_som25_sam02.sh
# sbatch cc_2_models_noeff_tweedie_low_egp_som25_sam005.sh
sbatch cc_2_models_noeff_tweedie_low_egp_som25_unequal.sh
sbatch cc_2_models_noeff_tweedie_low_egp_som50.sh
sbatch cc_2_models_noeff_tweedie_low_match.sh

sbatch cc_2_models_noeff_binary_high_egp_som10.sh
sbatch cc_2_models_noeff_binary_high_egp_som25.sh
# sbatch cc_2_models_noeff_binary_high_egp_som25_sam02.sh
# sbatch cc_2_models_noeff_binary_high_egp_som25_sam005.sh
sbatch cc_2_models_noeff_binary_high_egp_som25_unequal.sh
sbatch cc_2_models_noeff_binary_high_egp_som50.sh
sbatch cc_2_models_noeff_binary_high_match.sh

sbatch cc_2_models_noeff_binary_low_egp_som10.sh
sbatch cc_2_models_noeff_binary_low_egp_som25.sh
# sbatch cc_2_models_noeff_binary_low_egp_som25_sam02.sh
# sbatch cc_2_models_noeff_binary_low_egp_som25_sam005.sh
sbatch cc_2_models_noeff_binary_low_egp_som25_unequal.sh
sbatch cc_2_models_noeff_binary_low_egp_som50.sh
sbatch cc_2_models_noeff_binary_low_match.sh

